@startuml

title __BASE's Class Diagram__\n

  namespace be.kuleuven.travelrecipe {
    namespace base {
      class be.kuleuven.travelrecipe.base.CountryImageTranslation {
          - map : HashMap<String, String>
          + CountryImageTranslation()
          + generateFlag()
          + generateFlag()
      }
    }
  }
  

  namespace be.kuleuven.travelrecipe {
    namespace base {
      class be.kuleuven.travelrecipe.base.DatabaseConnect {
          - PICK_IMAGE_REQUEST : int
          - progressDialog : ProgressDialog
          - requestQueue : RequestQueue
          + DatabaseConnect()
          + addIngredient()
          + login()
          + postProfileImage()
          + register()
          + requestLikeState()
          + requestListRecipe()
          + requestRecipeDemo()
          + requestRecipeDetails()
          + retrieveAllCountries()
          + retrieveContinentInfo()
          + retrieveCountries()
          + retrieveCountryByContinent()
          + retrieveRecipes()
          + retrieveUserInfo()
          + setUserInfo()
          + uploadMealPlan()
          + uploadRecipe()
          + uploadStep()
          + uploadWork()
          - getResizedBitmap()
      }
    }
  }
  

  namespace be.kuleuven.travelrecipe {
    namespace base {
      interface be.kuleuven.travelrecipe.base.UsableDatabaseConnect {
          {abstract} + login()
          {abstract} + postProfileImage()
          {abstract} + register()
          {abstract} + requestLikeState()
          {abstract} + requestListRecipe()
          {abstract} + requestRecipeDemo()
          {abstract} + requestRecipeDetails()
          {abstract} + retrieveContinentInfo()
          {abstract} + retrieveCountries()
          {abstract} + retrieveCountryByContinent()
          {abstract} + retrieveRecipes()
          {abstract} + retrieveUserInfo()
          {abstract} + setUserInfo()
          {abstract} + uploadMealPlan()
          {abstract} + uploadRecipe()
          {abstract} + uploadStep()
          {abstract} + uploadWork()
      }
    }
  }
  

  be.kuleuven.travelrecipe.base.DatabaseConnect .up.|> be.kuleuven.travelrecipe.base.UsableDatabaseConnect
  be.kuleuven.travelrecipe.base.DatabaseConnect o-- be.kuleuven.travelrecipe.models.user.User : user


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
